Changes to restructure code branch
yavvorn/Spending-tracker pull request #2
Opened 2024-03-05 18:40 UTC by yavvorn

Changes that were made:

- main - using dictreader instead of csv reader
- added a func to calculate slice size
- added a line of code to set the background to grey

spending.csv - added title for each column

test_main - added simple unit tests

toml - started to use poetry as a dependency manager

the other 3 files are automatically generated

2024-03-06 11:27 UTC, slavovthinks requested changes
There are no installation instructions added to the README, there are no instructions on how to run the tests added to the README.
The `main.py` code is hard to test. 
It should be split in functions, also the classical `if __name__ == "__main__":` should be used. And all the code should be within a main function which gets called.
https://www.theserverside.com/tip/What-does-the-Python-if-name-equals-main-construct-do

2024-03-06 11:27 UTC, slavovthinks commented on install-pyenv-win.ps1
> +    .SYNOPSIS
Remove this file from the project. Whoever uses this project is responsible to install pyenv by himself if needed

2024-03-06 11:27 UTC, slavovthinks commented on tests/test_main.py
> +        totals = {}
this test doesnt test anything in main. It tests if the code written inside the test itself works properly.

2024-03-06 11:27 UTC, slavovthinks commented on tests/test_main.py
> +class TestCSVData(unittest.TestCase):
Tests cant execute at least on my machine

2024-03-06 11:27 UTC, slavovthinks commented on tests/test_main.py
> +        self.assertEqual(overall_usage.get('Food', 0), 163.0)
how is that expected to work?

2024-03-06 11:27 UTC, slavovthinks commented on spending.csv
> +Amount,Category
why capital letters?

2024-03-26 19:50 UTC, yavvorn commented
Have made the following changes alongside a fair bit of errors when it comes to commiting/pushing. 
Readme has been updated accordingly. 
main.py - now has appropriate functions with each action. 
test_main.py - now has appropriate unittests (The first two were created with the help of chatgpt).
Changed in the csv file the titles to lower letter.

2024-05-15 12:27 UTC, slavovthinks requested changes

2024-06-17 12:49 UTC, merged